/*
 * @lc app=leetcode id=389 lang=java
 *
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (53.06%)
 * Likes:    505
 * Dislikes: 230
 * Total Accepted:    146.9K
 * Total Submissions: 276.3K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * 
 */
class Solution {
    public char findTheDifference(String s, String t) {
        int len = s.length();
        char ret = t.charAt(len);

        for (int i = 0; i < len; i++) {
            ret ^= s.charAt(i);
            ret ^= t.charAt(i);
        }

        return ret;
    }

    public char findTheDifference2(String s, String t) {
        int sum = 0;

        for (char c : t.toCharArray()) {
            sum += c;
        }
        for (char c : s.toCharArray()) {
            sum -= c;
        }

        return (char)sum;
    }

    public char findTheDifference1(String s, String t) {
        int[] hash = new int[27];
        for (char c : s.toCharArray()) {
            hash[c - 'a']++;
        }

        char ret = ' ';
        for (char c : t.toCharArray()) {
            if (hash[c - 'a'] == 0) {
                ret = c;
                break;
            }
            hash[c - 'a']--;
        }

        return ret;
    }
}

